# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llama.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llama.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bllama.proto\x12\x05llama\"\x80\x01\n\x15\x43hatCompletionRequest\x12 \n\x08messages\x18\x01 \x03(\x0b\x32\x0e.llama.Message\x12\x12\n\nmax_tokens\x18\x02 \x01(\r\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\r\n\x05top_k\x18\x04 \x01(\r\x12\r\n\x05top_p\x18\x05 \x01(\x02\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\">\n\x16\x43hatCompletionResponse\x12\r\n\x05\x64\x65lta\x18\x01 \x01(\t\x12\x15\n\rfinish_reason\x18\x02 \x01(\t2_\n\x0cLlamaService\x12O\n\x0e\x43hatCompletion\x12\x1c.llama.ChatCompletionRequest\x1a\x1d.llama.ChatCompletionResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llama_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATCOMPLETIONREQUEST']._serialized_start=23
  _globals['_CHATCOMPLETIONREQUEST']._serialized_end=151
  _globals['_MESSAGE']._serialized_start=153
  _globals['_MESSAGE']._serialized_end=193
  _globals['_CHATCOMPLETIONRESPONSE']._serialized_start=195
  _globals['_CHATCOMPLETIONRESPONSE']._serialized_end=257
  _globals['_LLAMASERVICE']._serialized_start=259
  _globals['_LLAMASERVICE']._serialized_end=354
# @@protoc_insertion_point(module_scope)
